import { defineConfig } from 'vite';
import { fileURLToPath } from 'node:url';
import { existsSync, readdirSync } from 'node:fs';

const page = (name: string) => fileURLToPath(new URL(`./${name}.html`, import.meta.url));

// story/*.html pages are generated by scripts/generate-stories.mjs
// (part of `npm run build`) from published stories in Supabase.
const storyDir = fileURLToPath(new URL('./story', import.meta.url));
const storyInputs = existsSync(storyDir)
  ? Object.fromEntries(
      readdirSync(storyDir)
        .filter((file) => file.endsWith('.html'))
        .map((file) => [`story-${file.replace(/\.html$/, '')}`, fileURLToPath(new URL(`./story/${file}`, import.meta.url))])
    )
  : {};

export default defineConfig({
  base: '/bee/',
  build: {
    rollupOptions: {
      input: {
        main: page('index'),
        gallery: page('gallery'),
        stories: page('stories'),
        ask: page('ask'),
        game: page('game'),
        about: page('about'),
        admin: page('admin'),
        notfound: page('404'),
        ...storyInputs
      }
    }
  }
});
